### ISSUE TITLE
Adding contributors image list in readme

### ISSUE THREAD

**Issue by Arpcoder** [Muhammad-Owais-Warsi/Poemify#1]

**Comment by Muhammad-Owais-Warsi** [comment]
Assigned

**Comment by Muhammad-Owais-Warsi** [comment]
@Arpcoder , the images of the other contributors are not visible. Until then I'll just comment it down

**Comment by Muhammad-Owais-Warsi** [comment]
@Arpcoder provide me with your email

**Comment by Arpcoder** [comment]
> @Arpcoder provide me with your email

arpnakhandelwal@gmail.com

**Comment by Muhammad-Owais-Warsi** [comment]
> @Arpcoder , the images of the other contributors are not visible. Until then I'll just comment it down

.
