### ISSUE TITLE
Improve the Prompt and handle response

### ISSUE THREAD

**Issue by Muhammad-Owais-Warsi** [Muhammad-Owais-Warsi/Poemify#10]
Issue:  
1) The prompt currently used , generates the poem and title. If you have another better prompt , also how you'll handle both title and poem and display it on the page. The prompt can be found in the  " ./src/components/Input.tsx " at line 32

2) Is their any other way to generate poem??

**Comment by Prakash-Raut** [comment]
Hi, I would love to work on this issue.

**Solution**: Created a separate prompt for now.

![image](https://github.com/Muhammad-Owais-Warsi/Poemify/assets/82020300/e59eaa2e-8cfa-4690-b30f-7f38a86c51d0)

**Question**: How would you like to change the prompt ? Can you give any examples, if any, or should I go with this one.

**Followup**: I have also fixed a minor UI, which resulted in a better user experience. Should I create an issue first or fix it in the same PR ?

![image](https://github.com/Muhammad-Owais-Warsi/Poemify/assets/82020300/18211598-ba84-4245-baa6-ca60f5c0eca4)

Thank you for your guidance on this. Please let me know if there are any further improvements or considerations.

**Comment by Muhammad-Owais-Warsi** [comment]
@Prakash-Raut that's really great. You can raise the PR
