### ISSUE TITLE
Save and Share Options:

### ISSUE THREAD

**Issue by B8indu** [Muhammad-Owais-Warsi/Poemify#13]
Issue: Add functionality to save and share generated poems.
Description: Allow users to download the poem as a text file or image and share it directly on social media platforms.
Email: kb684874@gmail.com

**Comment by Muhammad-Owais-Warsi** [comment]
I'll assign this to you.

**Comment by Muhammad-Owais-Warsi** [comment]
You can change the explore button to save or share button. If you any other idea let me know 
![Screenshot_2024_0618_181609](https://github.com/Muhammad-Owais-Warsi/Poemify/assets/133518394/6629ee15-ddbc-490e-87a4-7eab1652dcc6)

**Comment by B8indu** [comment]
I need a Frontend javascript code of it..

**Comment by Muhammad-Owais-Warsi** [comment]
> I need a Frontend javascript code of it..

you can find that in ./src/components/poemCard.tsx

**Comment by Deepanshu-Bhati** [comment]
bro I have add the saved functionality

**Comment by Muhammad-Owais-Warsi** [comment]
@B8indu closing this issue
