### ISSUE TITLE
FEATURE: Adding a contact us page

### ISSUE THREAD

**Issue by RamakrushnaBiswal** [Muhammad-Owais-Warsi/Poemify#17]
**Is your feature request related to a problem? Please describe.**

Adding a contact us page

**Describe the solution you'd like**

**Email**
ramakrushnabunty@gmail.com

**Additional context**

**Comment by RamakrushnaBiswal** [comment]
@Muhammad-Owais-Warsi like we can add 
https://formbricks.com/

so  user contact with us

**Comment by Muhammad-Owais-Warsi** [comment]
Sure,I'll assign this to you
