### ISSUE TITLE
FEATURE: Creating a logo for the website

### ISSUE THREAD

**Issue by RamakrushnaBiswal** [Muhammad-Owais-Warsi/Poemify#18]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. 

**Describe the solution you'd like**

**Email**
ramakrushnabunty@gmail.com

**Additional context**

**Comment by RamakrushnaBiswal** [comment]
![image](https://github.com/Muhammad-Owais-Warsi/Poemify/assets/125277258/5c00bbb8-3ea7-4c7d-8be0-1c5f626cd6a1)

**Comment by Muhammad-Owais-Warsi** [comment]
Sure

**Comment by Muhammad-Owais-Warsi** [comment]
@RamakrushnaBiswal can you please show me the logo you designed.

**Comment by RamakrushnaBiswal** [comment]
![image](https://github.com/Muhammad-Owais-Warsi/Poemify/assets/125277258/ae3dd465-911e-4d08-99de-878c8956a347)

**Comment by RamakrushnaBiswal** [comment]
![image](https://github.com/Muhammad-Owais-Warsi/Poemify/assets/125277258/2abe3a48-4bf3-4999-be1f-78a5b3da6777)

**Comment by Muhammad-Owais-Warsi** [comment]
> ![image](https://private-user-images.githubusercontent.com/125277258/341161855-ae3dd465-911e-4d08-99de-878c8956a347.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4MjA1MzksIm5iZiI6MTcxODgyMDIzOSwicGF0aCI6Ii8xMjUyNzcyNTgvMzQxMTYxODU1LWFlM2RkNDY1LTkxMWUtNGQwOC05OWRlLTg3OGM4OTU2YTM0Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxOVQxODAzNTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wOGM3MmMwNjNkNDI5YmRiM2ZjNzliMzVjYTJiOGM2NWIzNWY3MzBlMDg1ZGM3ZDViNTAyZTViMDc3NDlmMDBmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.fMOXeRnHx2biEqhrgGF5vzNJpTB7PD_qwRe1CDogkC4)

This one looks cool.

**Comment by RamakrushnaBiswal** [comment]
ok then i will add and rise a PR
