### ISSUE TITLE
Adding a Login and Signup Page

### ISSUE THREAD

**Issue by Muhammad-Owais-Warsi** [Muhammad-Owais-Warsi/Poemify#19]
**Please describe.**
Currently there is no Login and Signup routes in the application.

**Describe the solution you'd like**
Add login and Signup route , may be a page before the main page opens up.

**Comment by shreyash3087** [comment]
@Muhammad-Owais-Warsi it should be functioning as well right? can we use next-auth with google oath provider for sign in?

**Comment by Muhammad-Owais-Warsi** [comment]
Only oauth is also fine.1) Google 2) GitHub(if possible)

**Comment by shreyash3087** [comment]
alright

**Comment by shreyash3087** [comment]
I made it work for localhost but for some reason its not working on vercel,and since I'm busy with gssoc right now i wont be able to give more time to this and find out what the issue is,will have to pass it to someone else

**Comment by Prakash-Raut** [comment]
I'm working on it now.
