### ISSUE TITLE
Delete the consoled response

### ISSUE THREAD

**Issue by Muhammad-Owais-Warsi** [Muhammad-Owais-Warsi/Poemify#2]
Issue :The response from the AI, get consoled  on the screen before it redirect to another page. 

How to reproduce the issue: Add an image and enter some prompt and then submit it, after sometime you'll see that the response is being consoled on the screen and then we get redirected to another page.

**Comment by Prakash-Raut** [comment]
Hi, I would love to work on this issue.

**Solution**: I have resolved the issue by ensuring that the redirection happens seamlessly, avoiding any unnecessary intermediate console logging. The redirection now occurs smoothly after handling the AI response, providing a better user experience.

**Followup**: Do you want me to remove the console.log() statements from the codebase ?. 

Thank you for your guidance on this. Please let me know if there are any further improvements or considerations.

**Comment by Muhammad-Owais-Warsi** [comment]
@Prakash-Raut , yes you have to remove the console.log() statement from codebase. Thanks for resolving the issue by ensuring the seamless redirection of page

**Comment by Muhammad-Owais-Warsi** [comment]
@Prakash-Raut please drop your email

**Comment by Prakash-Raut** [comment]
prakash_raut@outlook.com

**Comment by Muhammad-Owais-Warsi** [comment]
@Prakash-Raut using email, it is showing "not found", using which mail u registered in this hackathon
