### ISSUE TITLE
FEATURE : Adding a PreLoader to the Website

### ISSUE THREAD

**Issue by shreyash3087** [Muhammad-Owais-Warsi/Poemify#20]
**Is your feature request related to a problem? Please describe.**

The website Doesnt Have a Preloader

**Describe the solution you'd like**

Add a Minimilistic and Elegant Looking PreLoader to the Website that matches the Theme

![screencapture-localhost-3000-2024-06-18-21_49_47](https://github.com/Muhammad-Owais-Warsi/Poemify/assets/72603662/7a5f6338-5ffc-4f0d-8a50-1d88942f72e1)

**Email**
Enter your email: Shreyash3087@gmail.com

**Additional context**
N/A

**Comment by Muhammad-Owais-Warsi** [comment]
Sure 👍

**Comment by shreyash3087** [comment]
@Muhammad-Owais-Warsi sorry for the delay,was just busy with some stuff,when i was making the loader,i thought to look for some other loading animations as well,and got this other loader,what do you think of this-

**Originally Proposed Design-**


https://github.com/Muhammad-Owais-Warsi/Poemify/assets/72603662/e9768756-6026-4451-8d9e-30533e7fa3d7

**New Design -**

https://github.com/Muhammad-Owais-Warsi/Poemify/assets/72603662/15224cdf-1e38-4b4a-98af-f0129b757d73

**And Also a Dark Version (I really liked it tbh,looks cool)**

https://github.com/Muhammad-Owais-Warsi/Poemify/assets/72603662/3fda91d6-ff85-49b8-8a21-a376ce931d0f

**Which one would you like me to keep?,or if you dont like any of them i can search for some more**

**Comment by Muhammad-Owais-Warsi** [comment]
Really amazing work @shreyash3087 . I also liked the third design , looks really cool. Go on with that only

**Comment by Muhammad-Owais-Warsi** [comment]
Also is it possible to remove the white surrounding border???

**Comment by shreyash3087** [comment]
@Muhammad-Owais-Warsi  like this ?  -

https://github.com/Muhammad-Owais-Warsi/Poemify/assets/72603662/ab48d4ab-7361-484f-acb1-60dccab8a9f9

**Comment by Muhammad-Owais-Warsi** [comment]
Really amazing @shreyash3087
