### ISSUE TITLE
Addition of login and signup page fr the website

### ISSUE THREAD

**Issue by Aaryanb45** [Muhammad-Owais-Warsi/Poemify#29]
Also adding some pics and adding good css fr yr website

**Comment by Muhammad-Owais-Warsi** [comment]
Sure . Btw if you're VSoC Contributor , please drop your email

**Comment by Aaryanb45** [comment]
yh I am VSOC Contributor
aryanbansal182004@gmail.com

**Comment by Muhammad-Owais-Warsi** [comment]
Assigned
