### ISSUE TITLE
Better UI and Open-source Support

### ISSUE THREAD

**Issue by AKHegde22** [Muhammad-Owais-Warsi/Poemify#3]
The upgrade the existing ui and make the Poemify support open source models also along with gemini

**Comment by Muhammad-Owais-Warsi** [comment]
So basically what is the idea behind it?? What models you're going to use?

**Comment by AKHegde22** [comment]
to support other open source large language models through ollama

**Comment by Muhammad-Owais-Warsi** [comment]
Sure . I'll assign this to you

**Comment by Muhammad-Owais-Warsi** [comment]
@MRMORNINGSTAR2233 please provide me with your email

**Comment by AKHegde22** [comment]
pika5653@gmail.com

**Comment by Muhammad-Owais-Warsi** [comment]
@MRMORNINGSTAR2233 any updates ??

**Comment by AKHegde22** [comment]
currently i have exams till next wednesday ill soon be back on this surely
