### ISSUE TITLE
[Feature]:Improved Header And Addition of Footer on the Website

### ISSUE THREAD

**Issue by shreyash3087** [Muhammad-Owais-Warsi/Poemify#4]
**Description:**

Addition of a Proper Navbar and a footer would improve the overall user interface of the wesbite.

**Proposed Changes:**

- I would add a proper Navbar to the website that is completely responsive as well and contains buttons for home and contact us(which would redirect to our github page)
- Also add a footer with copyright message and link to github 

**Screenshots:**

N/A

**Additional Context:**

I am happy to contribute by implementing these features myself.Kindly Assign me the Issue

[X] I am a VSoC contributor

**Comment by Muhammad-Owais-Warsi** [comment]
Sure. I'll assign thi to you

**Comment by shreyash3087** [comment]
@Muhammad-Owais-Warsi Kept it simple,also added a temporary login and sign up button(doesnt work ofcourse),we could maybe add google oauth in future,do you want me change something or is it okay?

![screencapture-localhost-3000-2024-06-17-12_28_44](https://github.com/Muhammad-Owais-Warsi/Poemify/assets/72603662/f0f531e7-b836-48e6-93cd-afb1abb73ff8)

![screencapture-localhost-3000-2024-06-17-11_43_58](https://github.com/Muhammad-Owais-Warsi/Poemify/assets/72603662/b15ef343-7659-4093-9458-1810c13e6ca0)

**Comment by shreyash3087** [comment]
If its okay i can raise a PR

**Comment by Muhammad-Owais-Warsi** [comment]
@shreyash3087 , changes are okay, you can raise the PR.

**Comment by Muhammad-Owais-Warsi** [comment]
@shreyash3087 please drop your email

**Comment by shreyash3087** [comment]
@Muhammad-Owais-Warsi shreyash3087@gmail.com
