### ISSUE TITLE
Changes to improve: 

### ISSUE THREAD

**Issue by Mehak-Mattoo** [Muhammad-Owais-Warsi/Poemify#9]
1. change to background to more properly convey the website function. 2. properly explain the user what to do at homepage (img and text both required as right now , it think it will work with either one). 3. When the poem does get generated , dynamically change the background to text entered by user)

**Comment by Muhammad-Owais-Warsi** [comment]
These are really nice ideas.

**Comment by Muhammad-Owais-Warsi** [comment]
I'll assign this to to you

**Comment by Mehak-Mattoo** [comment]
Thanks

**Comment by Muhammad-Owais-Warsi** [comment]
Hey @Mehak-Mattoo please drop your email , for awarding points

**Comment by Mehak-Mattoo** [comment]
Sure, its mehakmattoo7@gmail.com

**Comment by Muhammad-Owais-Warsi** [comment]
@Mehak-Mattoo any updates on this??

**Comment by Mehak-Mattoo** [comment]
Haven't started yet, but will sure in 2-3 days.
